#server:
#  port: 8008
##  ${random.int[1024,9999]} 随机端口
##  servlet:
##    context-path: /sb  #配置初始路径
#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useAffectedRows=true&allowMultiQueries=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#        #2.连接池配置
#        #初始化连接池的连接数量 大小，最小，最大
#      initial-size: 10
#      min-idle: 10
#      max-active: 20
#        #配置获取连接等待超时的时间
#      max-wait: 60000
#        #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      time-between-eviction-runs-millis: 60000
#        # 配置一个连接在池中最小生存的时间，单位是毫秒
#      min-evictable-idle-time-millis: 30000
#      validation-query: SELECT 1 FROM DUAL
#      test-while-idle: true
#      test-on-borrow: true
#      test-on-return: false
#        # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#      filter:
#        stat:
#          merge-sql: true
#          slow-sql-millis: 5000
#        #3.基础监控配置
#      web-stat-filter:
#        enabled: true
#        url-pattern: /*
#          #设置不统计哪些URL
#        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
#        session-stat-enable: true
#        session-stat-max-count: 100
#      stat-view-servlet:
#        enabled: true
#        url-pattern: /druid/*
#        reset-enable: true
#        #设置监控页面的登录名和密码
#        login-username: admin
#        login-password: admin
#        allow: 127.0.0.1
#        #deny: 192.168.1.100
#
#  redis:
#    database: 0
#    host: 129.28.162.63
#    port: 6379
#    password: redis123456
#    timeout: 3000 #连接超时时间
#    jedis:
#      pool:
#        max-wait: -1 #阻塞最大等待时间，负值表示没有限制
#        max-active: 100 # 最大连接数，同上
#        max-idle: 10 #最大空闲连接
#        min-idle: 0
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
##    设置ack尝试次数
#    listener:
#      simple:
#        retry:
#          enabled: true
#          max-attempts: 5
#
#mybatis:
#classpath后面的 * 必不可少,，缺少型号的话后面的通配符不起作用。
#                **表示可以表示任意多级目录。
#如果mapper.xml文件放在resources中需要下面这行配置，如果和dao接口放在一个包中不需要
#  mapper-locations: classpath:mapper/*/*.xml
#  type-aliases-package: com.example.demo.po
#
#
#logging:
#  config: classpath:logback-spring.xml
#
#
##全局变量配置
#god: faker
#
#
#
#
